name: project flake8 cicd flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          # flake8 --max-line=250 $(git ls-files '*.py')
          # stop build process if having the error format Python or invalid name
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Max line is 250 character in 1 line (--exit-zero see the errors as warning)
          flake8 . --count --max-complexity=10 --max-line-length=250 --statistics